# Generated by Django 5.1.5 on 2025-01-26 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templates',
            old_name='templante_name',
            new_name='template_name',
        ),
    ]
