# Generated by Django 5.1.5 on 2025-02-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='section_type',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
