# Generated by Django 5.1.5 on 2025-02-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_content_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/'),
        ),
    ]
